### ISSUE TITLE
Generate a self contained token (JWT for instance)

### ISSUE THREAD

**Issue by thepeak99** [pondersource/surf-token-based-access#4]

**Comment by shokri-navid** [comment]
I choose this [ibrary](https://github.com/firebase/php-jwt) to generate the jwt token. It seems we need some ssl certificate to encode and decode the token.

**Comment by shokri-navid** [comment]
⚠ 
I will leave the SSL certificate by now an I will continue working encode and decode token using a simple SSL key. But we should figure it out to increase our security.

**Comment by navid-shokri** [comment]
ℹ 
It seems good schema for payload of our jwt token
https://jwt.io/libraries?language=PHP

**Comment by navid-shokri** [comment]
ℹ 
So, I write some tests for the `CertificateProvider` class and I will continue testing the `JWTHelper`.

**Comment by navid-shokri** [comment]
⚠ 
So the Issue subject should be changed because the plan has been changed. 

currently, we do not need to generate the token. some third party will issue it and we just need to verify it.
